### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by switchy7** [aoki-h-jp/funding-rate-arbitrage#16]
i have intslled by downoading package and then just pip install -r requirments.txt ... after packages were installed i run this command:
python fetch_funding_rate_all_exchanges.py - from examples folder but got error :
\examples\fetch_funding_rate_all_exchanges.py", line 4, in <module>
    from funding_rate_arbitrage.frarb import FundingRateArbitrage
ModuleNotFoundError: No module named 'funding_rate_arbitrage'
 What i am doing wrong?

**Comment by aoki-h-jp** [comment]
I apologise for any inconvenience caused.
I'm quite busy and will reply over the weekend.

**Comment by aoki-h-jp** [comment]
@switchy7 
There was a problem with setup.py, which caused pip installs to not work.
This problem has been resolved in the following commit. https://github.com/aoki-h-jp/funding-rate-arbitrage/commit/ddc35b14238fa733bc62e4337ffcdb6a2b94a9e9
Please try the following method on top of that.

```
~$ pip install git+https://github.com/aoki-h-jp/funding-rate-arbitrage
~$ vi example.py
~$ python3 example.py
```

The following code is saved as example.py in vi. (Exactly the same as fetch_funding_rate_all_exchanges.py)

```
"""
An example of fetching funding rate
"""
from funding_rate_arbitrage.frarb import FundingRateArbitrage

if __name__ == "__main__":
    # fetch from all exchanges
    fr = FundingRateArbitrage()
    for ex in fr.get_exchanges():
        print(ex)
        print(fr.fetch_all_funding_rate(exchange=ex))
```

**Comment by switchy7** [comment]
Hello, os have you time?

**Comment by aoki-h-jp** [comment]
@switchy7 
I'm busy these days, is there anything you would like me to develop additionally?

**Comment by switchy7** [comment]
sorry i have not seen your preveous answer, and is there a way to make auto trade for it/

**Comment by aoki-h-jp** [comment]
@switchy7 
I have plans to implement automatic funding rate arbitrage, but actually doing this trade by ourselves is surprisingly difficult due to the following points.

- I would like to take a position of generally more than $10,000 to make a large profit, but if I take such a position on the market, the order volume tends to be so large that it penetrates the board, and I end up losing money.
- Even if the same amount of orders are submitted to both Exchanges A and B at the limit price, they will not necessarily be executed, and if only one of them is executed, or if they are executed in a biased manner, funding rate arbitrage will fail.
- The same problem occurs when closing a position (but it is easier than when opening a position).

Therefore, we believe that full automation is more difficult than expected. If you have any ideas to improve the above, we would like to hear them.

**Comment by aoki-h-jp** [comment]
@switchy7 
Did you solve the first problem? If so, please close this issue.
If you have any ideas or requests for automation, please create another issue or post them in the discussion.

**Comment by switchy7** [comment]
i am so sorry i have been bussy thise days, can you please leave contact to talk about automation?

**Comment by aoki-h-jp** [comment]
@switchy7 
tg: @grandezooey
